src/css/Exercise.css
When the cursor hovers over the (play, edit, delete) buttons the cursor is changed to pointer type.
=> button cursor to pointer

src/containers/Builders/Template.js, src/containers/ExerciseList.js
In jsx background-color should be written as backgroundColor
Fixes #9
=> change background-color to backgroundColor

src/containers/Builders/CLOZEForm.js, src/containers/Builders/MCQForm.js, src/containers/Builders/REORDERForm.js, src/containers/translation.js
=> Exercise Title Added

src/containers/Router.js
I was going through Exerciser code as suggested [here](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2019.md). This code has the potential for further improvement. For the time being, I've removed unused parameters from the routes.
=> Unused parameters removed from routes

src/components/Exercise.js, src/components/Navbar.js, src/components/UserList.js, src/containers/Builders/CLOZEForm.js, src/containers/Builders/MCQForm.js, src/containers/Builders/REORDERForm.js, src/containers/Builders/Template.js, src/containers/Players/CLOZEPlayer.js, src/containers/Router.js, src/containers/Scores/PresenceScores.js, src/containers/Scores/Scores.js, src/containers/Sugarizer.js
Fixed all warnings from 'react-scripts'.
Before
After
@llaske, please review and give feedback #25
=> Fixed all warnings from 'react-scripts'

src/store/reducers/presence/sharedExercises.js
=> Only latest result of users in shared exercise

src/components/Navbar.js, src/components/UserList.js, src/containers/Builders/Template.js, src/containers/ExerciseList.js
This will fix #27 
@llaske, please review this request.
=> Change stateless class components to functional components

src/containers/Builders/MCQForm.js
=> Empty questions in MCQ fixed

src/containers/Builders/CLOZEForm.js, src/containers/Builders/MCQForm.js, src/containers/Builders/REORDERForm.js
=> input field default validation removed

src/containers/Builders/CLOZEForm.js, src/containers/translation.js, src/translations/en.json, src/translations/es.json, src/translations/fr.json
=> uneven number of blanks and clozes

src/components/Navbar.js
=> toggle home add button in navbar

src/containers/Sugarizer.js
=> edit enabled when activity reloaded from journal

src/containers/Builders/CLOZEForm.js, src/containers/translation.js, src/translations/en.json, src/translations/es.json, src/translations/fr.json
=> blanks cannot be reused in cloze form

src/components/Navbar.js
=> navbar-fix

src/containers/Sugarizer.js
=> remove default from shared exercise solved

src/components/Exercise.js, src/components/WithMultimedia.js, src/containers/Builders/FreeTextInputForm.js, src/containers/Builders/GroupAssignmentForm.js, src/containers/Builders/MCQForm.js, src/containers/Builders/MatchingForm.js, src/css/MatchingForm.css, src/icons/exercise/remove.svg
=> delete question added for all templates

src/css/GroupAssignmentForm.css, src/css/NewExerciseTemplate.css
=> fixed redundant scrollbar and added space below submit in sub activities

LICENSE
Updated license Copyright, specified Copyright as in other repositories.
=> Updated LICENSE Copyright

src/containers/Builders/CLOZEForm.js, src/containers/Builders/FreeTextInputForm.js, src/containers/Builders/GroupAssignmentForm.js, src/containers/Builders/MCQForm.js, src/containers/Builders/MatchingForm.js, src/containers/Builders/REORDERForm.js, src/containers/Builders/Template.js
Fixes: #101 
Added margin class in the buttons and cards for better spacing between them and to improve UI.
=> [Fixed issue #101] Improved the 'buttons' for exercises

src/containers/Players/GroupAssignmentPlayer.js
=> fixed-semicolon

src/containers/Scores/Scores.js, src/containers/translation.js
=> Add tooltip to the result page

src/containers/Scores/PresenceScores.js, src/containers/Scores/Scores.js
=> Added labelling to axes, made graph dynamic

src/containers/Sugarizer.js
I have added the functionality to save the exercise when the new instance of exercise is loaded.
Issue: #100
=> Recover the exercise if accidentally shut down

src/containers/Players/MCQPlayer.js, src/css/MCQPlayer.css
=> fix: MCQ answers should be in rows

src/css/FreeTextInputPlayer.css, src/css/GroupAssignmentPlayer.css, src/css/MCQPlayer.css, src/css/MatchingPlayer.css, src/css/PresenceScores.css
=> UI improvements

src/css/index.css
hey @llaske, I have made some mistakes due to some confusion in my previous PR(#149),
this is new fix for issue: #148
=> Extension of PR #149 : Issue fixed of activity description box

src/css/MCQPlayer.css
=> Fixed UI issue

src/store/index.js
=> remove redux dev tools

src/containers/Players/MCQPlayer.js
=> fixed MCQPlayer not showing results in real-time eval mode

src/containers/Players/MatchingPlayer.js
=> fixed exerciser crash on clicking results in Mathing-pairs realtime eval

src/containers/Players/MatchingPlayer.js
@llaske Fixes :
I tested it with every possible break it works perfectly.
=> maching player able to match from both sides.

src/components/Navbar.js
=> fixed exerciser error on run all exerciser 

src/containers/Scores/ScoreHoc.js
=> fix: incorrect information on score details screen

src/containers/Players/MatchingPlayer.js
=> Fixed matching dots displace on screen resize and full screen

src/css/Exercise.css
@llaske keeping your points into consideration given in [#174](https://github.com/llaske/ExerciserReact/pull/174), i updated it.
=> Enhancement of drag list

src/components/Navbar.js, src/containers/Sugarizer.js
=> fix: run all skips first exercise and run all not working in evaluation mode
